spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  application:
    name: Aroom-BE

  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
